Vagrant.configure("2") do |config|
    config.vm.box = "generic/centos8"
    config.vm.define "nharraS" do |control|
        control.vm.hostname = "nharraS"
        control.vm.network "private_network", ip: "192.168.42.110"
        control.vm.provider "virtualbox" do |v|
            v.customize ["modifyvm", :id, "--name", "nharraS"]
            v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
            v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
            v.memory = 2048
            v.cpus = 1
        end
        control.vm.provision "shell", path: "scripts/install_kubectl.sh"
        control.vm.provision "shell", path: "scripts/server.sh"
    end
    config.vm.define "czenaSW" do |control|
        control.vm.hostname = "czenaSW"
        control.vm.network "private_network", ip: "192.168.42.111"
        control.vm.provider "virtualbox" do |v|
            v.customize ["modifyvm", :id, "--name", "czenaSW"]
            v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
            v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
            v.memory = 2048
            v.cpus = 1
        end
        control.vm.provision "shell", path: "scripts/install_kubectl.sh"
        control.vm.provision "shell", path: "scripts/server.sh"
    end
end